### PR TITLE
run one example using mute mode 

### PR DESCRIPTION
**Pull request by thinkerou**
Hi, @macchiatow please review the pr, I think we should use mute mode and use <className> as the name of the simulation to be run, what about?

### CODE REVIEW

**Comment by thinkerou** [comment]
Default only run blocking simulation case, if user want to use other simulation case which should be rewrite. 
About error, sorry, I will fix later on.

**Comment by macchiatow** [comment]
not sure if it's best. I  believe one should be forced to change code (even Dockerfile) to run smoke test. Yet it is still possible to rewrite --entrypoint during image run command.

**Comment by thinkerou** [comment]
my real intention want to debug and check one simulation case result, as you say, if run smoke test it should run all simulation case, so only use `mute` mode.

**Comment by macchiatow** [comment]
sh: can't open '/opt/gatling/bin/gatling.sh -m'

**Comment by thinkerou** [comment]
On Docker the `-m` command of gatling invalid, we still need to input simulation number.

**Pull request merged**
